version: '3.8'

services:
  vendor_app:
    build: .
    container_name: vendor_app
    volumes:
      - ./app:/app/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file:
      - .env

  redis:
    image: redis:7.2
    container_name: redis
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: vendor_orders 
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis_consumer:
    build: .
    container_name: redis_consumer
    depends_on:
      - redis
      - db
    volumes:
      - ./app:/app/app
    command: ["python", "-u", "app/consumers/redis_consumer.py"]
    env_file:
      - .env

volumes:
  pgdata:
